title: Daniele Conserva
logo: /assets/img/logo.jpg

description: A portfolio page about me and my work.
favicon: true
color-scheme: auto

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/danieleconserva

navigation:
  - name: My Work 
    link: ./index.html
    sublist:
      - name: F1 telemetry
        link: ./work.html#formula-1-telemetry-app
      - name: Short video generator
        link: ./work.html#automatic-short-video-generator
      - name: Complete data infrastructure
        link: ./work.html#complete-data-infrastructure
      - name: Brain aneurysm detection model
        link: ./work.html#brain-aneurysm-detection-model
      - name: Garage manager pro
        link: ./work.html#garage-manager-pro
      - name: Electronic devices and products
        link: ./work.html#electronic-devices-and-products

  - name: Certifications
    link: ./certs.html
  - name: About me
    link: ./aboutme.html
