title: Daniele Conserva
logo: /assets/img/logo.jpg

description: A portfolio page about me and my work.
favicon: true
color-scheme: auto

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/danieleconserva
  - name:  
  - name: Download my text only CV
    icon: <i class="fas fa-file-pdf"></i>
    link: https://scorpiogt.github.io/dani.cons/assets/docs/cv_text.pdf
  - name: Download my visual CV
    icon: <i class="fas fa-file-pdf"></i>
    link: https://scorpiogt.github.io/dani.cons/assets/docs/cv_visuals.pdf


navigation:
  - name: My Work 
    link: ./index.html
    sublist:
      - name: Corporate
        link: ./index.html#corporate-work
      - name: Personal
        link: ./index.html#personal-projects-work
  - name: Certifications
    link: ./certs.html
  - name: About me
    link: ./aboutme.html
