title: Daniele Conserva
logo: /assets/img/logo.jpg
email: person@address.com
description: A portfolio page about me and my work.
favicon: true
color-scheme: auto

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/danieleconserva

navigation:
  - name: My Work 
    link: ./work.html
    sublist:
      - name: F1 telemetry
        link: ./work.html#formula-1-telemetry-app
  - name: Certifications
    link: ./certs.html
  - name: About me
    link: ./index.html
